### ISSUE TITLE
Funding common pool resources

### ISSUE THREAD

**Issue by chadwhitacre** [chadwhitacre/openpath#14]
Follow-up to #9. Share thoughts on Governing the Commons, social pressure, taxation in the limit. Discuss whether we need new institution(s) and what those might look like.

[Interest here](https://lobste.rs/s/sm3t1o/open_source_sustainability_crisis).

**Comment by chadwhitacre** [comment]
> I think open source is not sustainable because it is intrinsically at odds with the system it lives within. The article mentions it but doesn’t go deeper into that. Our current economic system rewards profit in the short term over wellbeing and long term sustainability.
>
> Unless the incentives change, I don’t think this can improve for services offered freely. “The path lies through platforms” is patching the issue with charity, and I don’t think it will bring real long term change.
>
> The path lies through an overhaul of our economic systems.

https://lobste.rs/s/sm3t1o/open_source_sustainability_crisis#c_hr3zrw

**Comment by chadwhitacre** [comment]
Adjacent suggestion:

> i'm not suggesting that. i'm thinking out loud that the open source community that already builds the roads that moves their software also build the mechanisms that create a 'tax'

https://twitter.com/motdotla/status/1749597995107221539

**Comment by coni2k** [comment]
Excellent, subscribed to the thread! 👍

Let me share the SustainOSS Discourse post that has a few more details, including how an invoice should look with an #OpenSourceTax:
https://discourse.sustainoss.org/t/sustain-together-october-summary/1125/6?u=coni2k

**Comment by chadwhitacre** [comment]
Under https://github.com/chadwhitacre/openpath/issues/19#issuecomment-1908772281, I learned about a paper that seems relevant to this thread: "[The sustainability of open source commons](https://www.tandfonline.com/doi/epdf/10.1080/0960085X.2022.2046516)."

**Comment by chadwhitacre** [comment]
Maybe bring up [tea.xyz](https://tea.xyz/)?

E.g. https://twitter.com/bidah/status/1750637228856889537

(I had a call with the Tea guys.)

**Comment by chadwhitacre** [comment]
TIL https://www.opencontributions.dev/about from @JoshuaKGoldberg:

> That page has a summary of where we left it: the quantifying would be done as a 2x2 grid of:
> * Contribution type: employee time / financial
> * Contribution area: community / the company's
>
> Most companies won't do anything unless they're pressured to, and I think having a restaurant-health-code-style agreed-upon grade has a lot of potential for becoming that pressure... *if* the community can agree on it and take actions to enforce that pressure.

**Comment by chadwhitacre** [comment]
From @gordonbrander at https://github.com/chadwhitacre/openpath/issues/20#issuecomment-1934276031:

> From a narrative perspective, I suspect "sustainability/fair share" frame might encourage zero-sum thinking. "Our slice of the pie". From my perspective, the pie isn't fixed. Rather, we're looking at a broken feedback loop and a resulting ecological desert.
> 
> Open source lowers the floor for startups to get to product-market fit, generating money
> However, very little of that money makes it back to the funding of open source
> Closing the loop means more open source funding means more open source developers surviving means more open source means lower floor means more startups means more funding...
> There's probably some upper limit to this positive ecological feedback, defined by the rate at which a market can absorb new products, but I doubt we've reached that yet. Rather, [we seem to be limited at the level of fundamental research / new low-cost enablers](https://www.amazon.com/Doing-Capitalism-Innovation-Economy-Reconfiguring/dp/1108471277) due to lack of non-speculative funding. Low-cost enablers are what open source is all about. Let's terraform the ecological desert :)

**Comment by chadwhitacre** [comment]
https://redmonk.com/sogrady/2018/09/10/tragedy-of-the-commons-clause/
https://github.com/getsentry/fsl.software/issues/2#issuecomment-1942070434
https://twitter.com/_msw_/status/1757494720924639636 etc.

**Comment by mswilson** [comment]
Recommend reading https://www.brookings.edu/articles/strengthening-digital-infrastructure-a-policy-agenda-for-free-and-open-source-software/ that outlines a policy agenda to help support FOSS and generally increase the provision of digital public goods. It covers things like taxes and incentives.

**Comment by ShaneCurcuru** [comment]
Oh hey GH Issues to discuss blog ideas, nice.

Came here to say: some of the issues with "pay the maintainer" and related needs is tax policy and banking laws, along with education thereof - that's a lower level need in a way than the "explain to $BigCos how paying maintainers is a good business decision".

How do we better explain the difficulties individual workers have in actually getting funds?  I knew to setup an LLC in my home state before doing consulting; many people don't realize this.  It was a number of paperwork, small fees, and learning and tooling hoops to use a business bank account, get quickbooks, know how to write an invoice, etc.  

This feels like there should be a whole bunch of different policy and education changes that would enable more individuals to participate as individuals in capitalism for their work, but it's so many different touchpoints it's hard to discuss.  Going from a (in the US) W-2 worker to getting a bunch of 1099s is a lot of work and extra knowledge beyond building great software.  How do we really signpost and make the journey easier, along with efficiently advocating for policy and educational change?

**Comment by chadwhitacre** [comment]
Bringing this over from @mswilson at https://github.com/getsentry/fsl.software/issues/2#issuecomment-1942070434:

> A "[Commons](https://en.wikipedia.org/wiki/Commons)" is a specific thing in the literature. It's something where multiple people benefit from resources that are accessible to all.
> 
> In the realm of software development (and other cooperative efforts), there is a studied phenomenon called "[commons-based peer production](https://en.wikipedia.org/wiki/Commons-based_peer_production)." The goods that are produced at the center of commons-based peer production are available for the benefit of many stakeholders.
> 
> One problem with attaching a "Common Source Software" label onto goods that are made available under FSL is that the commercial benefits accrue to the _sole producer_ of that good. Those goods aren't even [club goods](https://en.wikipedia.org/wiki/Club_good). They don't enrich the public commons of software until 2 years after release.
> 
> It's [Freeware](https://en.wikipedia.org/wiki/Freeware) with accompanying source code, until the time when it is available under a FOSS license.
> 
> I worry that if you proceed down the "Commons" path, you will provoke some ire from the open source community anyway, similar to [responses](https://redmonk.com/sogrady/2018/09/10/tragedy-of-the-commons-clause/) to the "Commons Clause"

**Comment by chadwhitacre** [comment]
> Oh hey GH Issues to discuss blog ideas, nice.

😁 🙇 

> How do we really signpost and make the journey easier, along with efficiently advocating for policy and educational change?

For my part I think we need a new institution that takes most of the bureaucratic burden off of individual developers. I think [the answer lies through platforms](https://openpath.chadwhitacre.com/2024/the-open-source-sustainability-crisis/#the-path-lies-through-platforms) but I don't think the existing platforms are sufficient.

**Comment by chadwhitacre** [comment]
Bringing this over from https://github.com/getsentry/fsl.software/issues/2#issuecomment-1977433883: 

> Ostrom's framework for developing institutions that prevent tragedies of commons ([Governing the Commons](https://www.amazon.com/dp/1107569788), p. 90) is precisely about developing and enforcing rules for who may take resources from the common pool, and under what conditions. Successful CPR management comes from evolving norms of quasi-exclusivity to prevent overuse, enforced by collectively governed institutions. Moreover, these "[i]nstitutions are rarely either private or public - 'the market' or 'the state.' Many successful CPR institutions are rich mixtures of 'private-like' and 'public-like' institutions defying classification in a sterile dichotomy" (p. 14).

**Comment by chadwhitacre** [comment]
> "[The sustainability of open source commons](https://www.tandfonline.com/doi/epdf/10.1080/0960085X.2022.2046516)."

I read/skimmed this paper. It is working with an extremely broad definition of sustainability, reviewing the literature to fit various approaches into an overarching taxonomy. The exercise feels more akin to what @mswilson is calling _resilience_, and is rather far removed from [the definition of sustainability I am working with](https://openpath.chadwhitacre.com/2024/the-open-source-sustainability-crisis/#what-is-open-source-sustainability):

> Open Source sustainability is when any smart, motivated person can produce widely adopted Open Source software and get paid fairly without jumping through hoops.

### Which Commons?

I was glad to learn of [_Understanding Knowledge As a Commons: From Theory to Practice_](https://www.amazon.com/dp/0262083574) from this paper. I've only read [_Governing the Commons_](https://www.amazon.com/dp/1107569788) from Elenor Ostrom and have [wondered](https://github.com/getsentry/fsl.software/issues/2#issuecomment-1977433883) how we got from "commons" as non-exclusive/rivalrous to "digital commons" as non-exclusive/_non_-rivalrous. Maybe this book holds a clue, though the paper also suggests a path that lies through Yochai Benkler (p. 765):

> In fact, Benkler (2014, p. 71) calls for distinguishing the existence of two broad paradigms of commons' regimes: the bounded commons, best exemplified by CPRs, and the "open commons", characterised by "freedom to operate under symmetric constraints, available to an open, or undefined, class of users", including for example, roads, urban sidewalks, public utilities or, indeed open source software.

Here is [Benkler 2014](https://www.benkler.org/Commons_Unmodified_Benkler.pdf). Indeed there are further pointers. Dialing back out from that rabbit hole, though, I prefer Nadia Asparouhova's distinction in [_Working in Public_](https://www.amazon.com/dp/0578675862) to Benkler's(?) conflation. "[T]here are two economic goods in open source masquerading as one. Open source code is _consumed_ like a public good, [but] is _produced_ like a commons, where a maintainer's attention is the limited resource" (p. 212).

When I talk about software commons (where #2 is ending up), I mean the latter of these: the common pool resource of maintainer attention. Open Source sustainability is when any any smart, motivated person can produce widely adopted Open Source software and get paid fairly without jumping through hoops. Attention is time and time is money. To solve Open Source sustainability, we should tackle it as a classic CPR institutional design challenge.

**Comment by ShaneCurcuru** [comment]
Met a bunch of people at FOSSBackstage who might be interested here as well.  I also presented briefly my aspects of sustainability: one thing I'd find useful is a rough mapping taxonomy between the different constituencies we need to work with on software sustainability (I'm thinking social / fiscal / organizational / software ecosystem here, not necessarily ecology specifically).  We're each going to come up with messages for specific groups; it would be great to have some signposting of how to translate those messages for reuse with other groups.

https://fosssustainability.com/aspects/?s=g

**Comment by chadwhitacre** [comment]
I'm going to close this with "[Open-Source Software Is in Crisis](https://spectrum.ieee.org/open-source-crisis)."
