### ISSUE TITLE
Post-scarcity economics

### ISSUE THREAD

**Issue by chadwhitacre** [chadwhitacre/openpath#15]
Follow-up to #9.

> Open Source is designed for a different world. It presents the first real opportunity in our society to begin to develop a post-scarcity economic model at scale. That likely wants unpacking in a future post.

https://openpath.chadwhitacre.com/2024/the-open-source-sustainability-crisis/#whats-wrong-with-hoops

**Comment by chadwhitacre** [comment]
> I think open source is not sustainable because it is intrinsically at odds with the system it lives within. The article mentions it but doesn’t go deeper into that. Our current economic system rewards profit in the short term over wellbeing and long term sustainability.
>
> Unless the incentives change, I don’t think this can improve for services offered freely. “The path lies through platforms” is patching the issue with charity, and I don’t think it will bring real long term change.
>
> The path lies through an overhaul of our economic systems.

https://lobste.rs/s/sm3t1o/open_source_sustainability_crisis#c_hr3zrw

**Comment by chadwhitacre** [comment]
Maybe get into [twyw](https://opensource.com/open-organization/16/7/compensating-employees-letting-them-take-what-they-want) and governance? From Josh Simmons in TODO Slack:

> [Good read](https://openpath.chadwhitacre.com/2024/the-open-source-sustainability-crisis/). Something that is brushed up against in this, maintainer burnout, could take us a little deeper into the problem space. Funding alone isn't a solution -- a maintainer may know how to put it to work to buy themselves time and meet their personal needs, but a maintainer practically needs to be a mini Executive Director in order to figure out how to use those funds to make sure the project will outlast their own involvement.
>
> I'd argue that unless we also address governance, and provide supportive services to maintainers to shore up all the skills they can't or don't want to bring to the table, on top of providing funding, we are not going to make a meaningful dent in this systemic problem.
>
> To put a finer point on it, it's not just the lack of funding that is between us and a future in which the open source projects we all depend on are sustainable. It's also questions of succession planning, leadership development, governance, and stewardship. (And chances are FOSS foundations are a critical puzzle piece...)

**Comment by chadwhitacre** [comment]
Too high-flown / abstract. Dropping for now.

**Comment by vladh** [comment]
Helpful resources in the economics literature:

* Open Source software is a [positive production externality][ppe]
* “[The Economics of Technology Sharing: Open Source and Beyond][tirole]” by Josh Lerner and Jean Tirole, particularly p 102–105
* “[The Success of Open Source][weber]” by Steven Weber, particularly p 149–156 (gift economy, public good, positive network externalities); p 227–231 (property rights); p 231–243 (distributed innovation); p 243–248 (tragedy of the commons, positive externalities, meaningful work)
* Open Source is not a gift economy (see Weber p 149–156)

[ppe]: https://en.wikipedia.org/wiki/Externality#Positive
[tirole]: https://www.aeaweb.org/articles?id=10.1257%2F0895330054048678
[weber]: https://www.hup.harvard.edu/books/9780674018587
