### ISSUE TITLE
Openwashing - is it real?

### ISSUE THREAD

**Issue by chadwhitacre** [chadwhitacre/openpath#18]
Open washing - find examples of Sentry being called this - what's the definition? Is it real? What are classic cases? Has it actually happened?

([private doc 🔒](https://docs.google.com/document/d/1fmj7lIjwpKvenfnmn0pVlc9Ebw6iQMcc/edit?usp=sharing&ouid=104794135922783582883&rtpof=true&sd=true), forthcoming [podcast](https://tractable.withorb.com/episodes) transcript, @selviano riffs on open-washing in the comments)

**Comment by selviano** [comment]
https://en.wikipedia.org/wiki/Openwashing

**Comment by chadwhitacre** [comment]
With the move to [Fair Source](https://fair.io/) we have no dog in this fight anymore.
