### ISSUE TITLE
OSS and AI - what's up?

### ISSUE THREAD

**Issue by chadwhitacre** [chadwhitacre/openpath#21]
OSI has [a thing](https://opensource.org/deepdive/). Heather has a thing. Digest, look around for other, develop an opinion.

Good/necessary for media inquiries/placement.

**Comment by selviano** [comment]
https://twitter.com/GergelyOrosz/status/1734463656102969345

**Comment by chadwhitacre** [comment]
sustainability and privacy/security tie-ins?

**Comment by chadwhitacre** [comment]
Honestly hard for me to care. Not my jam. Maybe it will be some day?
