### ISSUE TITLE
Link points to localhost

### ISSUE THREAD

**Issue by extua** [chadwhitacre/openpath#30]
A small link issue, in [this post](https://openpath.chadwhitacre.com/2024/funding-the-five-thousand/), the link [here](https://github.com/chadwhitacre/openpath/blob/4d3a7e3313e791b026a7600a360e7c725b10017d/_posts/2024-02-05-funding-the-five-thousand.md?plain=1#L15) points to localhost

http://localhost:4000/2024/questioning-the-value-of-open-source-software/

and could be changed to

https://openpath.chadwhitacre.com/2024/questioning-the-value-of-open-source-software/

Incidentally, jekyll has a [post_url tag](https://jekyllrb.com/docs/liquid/tags/#linking-to-posts) which handles internal links to posts and might be useful here.

**Comment by chadwhitacre** [comment]
Oops! Thanks @extua, fixed in 95fe40366682e1217cdd55ede50e120dfbaf107b and [deploying](https://github.com/chadwhitacre/openpath/actions/runs/8398734420).

These keep slipping in, I should write a PR check or something. 😅

**Comment by chadwhitacre** [comment]
Deployed and confirmed. Thanks again! ☺️

**Comment by chadwhitacre** [comment]
> Incidentally, jekyll has a [post_url tag](https://jekyllrb.com/docs/liquid/tags/#linking-to-posts) which handles internal links to posts and might be useful here.

Hmmm ... maybe. 🤔
